language: node_js

node_js:
  - "8"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.28.1

before_script:
  - yarn run bootstrap

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov/bin/codecov

cache: yarn
