language: node_js

node_js:
  - "8"

cache:
  directories:
    - node_modules

before_install:
  - yarn install codecov

before_script:
  - yarn run bootstrap

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov/bin/codecov

cache: yarn
