language: node_js

node_js:
  - "8"

before_script:
  - yarn run bootstrap

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov/bin/codecov

script: npm run test

cache:
  directories:
    - node_modules